name: Sync External Repositories

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync_repositories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
    
    - name: Set Git user info
      run: |
        git config user.name "harryzhaozy"
        git config user.email "harryzhaozy@hotmail.com"

   
    - name: Clone and sparse checkout kwrt-packages
      run: |
        git clone --depth=1 https://github.com/kiddin9/kwrt-packages.git kwrt-packages
        cd kwrt-packages
        git sparse-checkout init --cone
        git sparse-checkout set luci-app-accesscontrol luci-app-airconnect airconnect luci-app-airplay2 luci-app-argon-config luci-theme-argon luci-app-autoreboot luci-app-diskman luci-app-dnsfilter luci-app-homeproxy luci-app-mosdns mosdns v2dat luci-app-nfs luci-app-openvpn-server openvpn-dns-hotplug luci-app-quickstart quickstart luci-app-store luci-lib-taskd luci-lib-xterm taskd luci-app-systools luci-lib-iform luci-lib-taskd speedtestcli luci-app-usb-printer
        cd ..
        for dir in luci-app-accesscontrol luci-app-airconnect airconnect luci-app-airplay2 luci-app-argon-config luci-theme-argon luci-app-autoreboot luci-app-diskman luci-app-dnsfilter luci-app-homeproxy luci-app-mosdns mosdns v2dat luci-app-nfs luci-app-openvpn-server openvpn-dns-hotplug luci-app-quickstart quickstart luci-app-store luci-lib-taskd luci-lib-xterm taskd luci-app-systools luci-lib-iform luci-lib-taskd speedtestcli luci-app-usb-printer; do
          if [ -d "$dir" ]; then
            if [[ "$(diff -qr kwrt-packages/$dir $dir)" ]]; then
              echo "Changes detected in $dir, syncing..."
              rm -rf $dir
              mv kwrt-packages/$dir $dir
            else
              echo "No changes detected in $dir, skipping..."
            fi
          else
            echo "Directory $dir does not exist, creating and syncing..."
            mv kwrt-packages/$dir $dir
          fi
        done
        rm -rf kwrt-packages

    - name: Clone and sync luci-app-qbittorrent
      run: |
        git clone --depth=1 https://github.com/sbwml/luci-app-qbittorrent.git temp_luci-app-qbittorrent
        for dir in luci-app-qbittorrent qbittorrent qt6base qt6tools rblibtorrent; do
          if [ -d "$dir" ]; then
            if [[ "$(diff -qr temp_luci-app-qbittorrent/$dir $dir)" ]]; then
              echo "Changes detected in $dir, syncing..."
              rm -rf $dir
              mv temp_luci-app-qbittorrent/$dir $dir
            else
              echo "No changes detected in $dir, skipping..."
            fi
          else
            echo "Directory $dir does not exist, creating and syncing..."
            mv temp_luci-app-qbittorrent/$dir $dir
          fi
        done
        rm -rf temp_luci-app-qbittorrent

    - name: Commit changes (if any)
      run: |
        git add .
        git diff --cached --quiet || git commit -m "Sync external repositories"
        git push
   
        
    #- name: Commit changes (if any)
    #  run: |
    #    git add .
    #    git diff --cached --quiet || git commit -m "Sync external repositories"
    #    git push https://x-access-token:${{ secrets.MY_PAT_TOKEN }}@github.com/harryzhaozy/luci-packages.git main

   
